"""
Django settings for Precvadi project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!=g)_8e)6##-&o4x^$w%mgd+_9=b^bsm+=g$j!3od%m^i0xu#='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

#X_FRAME_OPTIONS = 'SAMEORIGIN'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp.apps.MyappConfig',
    'compte.apps.CompteConfig',
    'ckeditor',
    'das',
    'home',
    'foncier',
    'education',
    'peche',
    'sante',
   
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Precvadi.urls'



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',   
        'DIRS':['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Precvadi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
   'default': {
       'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
#DATABASES = {
   # 'default': {
   #     'ENGINE': 'django.db.backends.postgresql',
    #    'NAME':' precvadi',
   #     'USER': 'admin',
   #     'PASSWORD': 'a',
   #     'HOST': 'localhost',
   #     'PORT': '5432',
   #     'OPTIONS': {'sslmode':'disable'},
 #  }
#}
#DATABASES = {
  #  'default': {
   #'ENGINE'  : 'django.db.backends.mysql',  
    #  'NAME'    : 'DimPecheArtisan',                
     #   'USER'    : 'root',                   
      #  'PASSWORD': 'root',              
       # 'HOST'    : 'localhost',               
       # 'PORT'    : '3306',
   ## }
#}

#
#DATABASES = {
 #   'default': {
  #  'ENGINE'  : 'django.db.backends.mysql', 
    #  'NAME'    : 'test',                  
      #  'USER'    : 'root',                  
        #'PASSWORD': 'root',         
       # 'HOST'    : 'localhost',                
       # 'PORT'    : '3306',
    #}
#}

#DATABASES = {
   # 'default': {
   # 'ENGINE'  : 'django.db.backends.mysql', 
    #  'NAME'    : 'foncier',                 
      #  'USER'    : 'root',                     
       # 'PASSWORD': 'root',              
        #'HOST'    : 'localhost',                
        #'PORT'    : '3306',
    ###}
#}
# 
# DATABASES['default'] =  dj_database_url.config()

#
    
   # 'agriculture': {
     #   'NAME': 'agriculture',
      #  'ENGINE': 'django.db.backends.mysql',
       # 'USER': 'root',
       # 'PASSWORD': '',
        #'HOST'    : 'localhost', 
       # 'PORT': '3306',
    #},
    
#}
 #DATABASES = {
   # 'default': {
     #   'ENGINE': 'django.db.backends.sqlite3',
     #    'NAME': BASE_DIR / 'db.sqlite3',
   #  }
 #} 


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT ='/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'static')
]
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL ='posts:tabview'
LOGIN_URL = 'compte:login'