# Generated by Django 4.1.6 on 2023-02-08 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimFoncier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeFoncier', models.CharField(max_length=300)),
                ('StatuFoncier', models.CharField(max_length=300)),
                ('TerrDeclas5D_Ans', models.CharField(max_length=300)),
                ('ActFonciePresen', models.CharField(max_length=300)),
                ('TxtFoncier', models.CharField(max_length=300)),
                ('OutilGesFoncier', models.CharField(max_length=300)),
                ('TypeConflit', models.CharField(max_length=300)),
                ('TypeUsage', models.CharField(max_length=300)),
                ('ExistCadrConcert', models.CharField(max_length=300)),
                ('EchelCadrConcert', models.CharField(max_length=300)),
                ('Entrepris_Indust_IncidFonc', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DimFoncierGouvernanc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LoiReglement', models.CharField(max_length=300)),
                ('OutilSecuriseFoncie', models.CharField(max_length=300)),
                ('ActFoncier', models.CharField(max_length=300)),
                ('DegreConnaissanc', models.CharField(max_length=300)),
                ('NivComprehension', models.CharField(max_length=300)),
                ('Resume', models.CharField(max_length=300)),
                ('AtelierBonInformat', models.CharField(max_length=300)),
                ('SecuritAjout', models.CharField(max_length=300)),
                ('ActImplique', models.CharField(max_length=300)),
                ('CauseAvance', models.CharField(max_length=300)),
                ('SolutionPropose', models.CharField(max_length=300)),
                ('SolutionRetenu', models.CharField(max_length=300)),
                ('VerificatProcedur', models.CharField(max_length=300)),
                ('ControlPermanant', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DimGeographie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeCommune', models.IntegerField()),
                ('nomCommune', models.CharField(max_length=300)),
                ('CodeIndicateur', models.IntegerField()),
                ('Indicateur', models.CharField(max_length=300)),
                ('CodeDomaine', models.IntegerField()),
                ('NomDomaine', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DimTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Jour', models.CharField(max_length=300)),
                ('AnneeCode', models.IntegerField()),
                ('AnneeDate', models.DateField()),
                ('AnneeNom', models.CharField(max_length=300)),
                ('SemestreCode', models.IntegerField()),
                ('SemestreDate', models.DateField()),
                ('SemestreNom', models.CharField(max_length=300)),
                ('TrimestreCode', models.IntegerField()),
                ('TrimestreDate', models.DateField()),
                ('TrimestreNom', models.CharField(max_length=300)),
                ('MoisCode', models.IntegerField()),
                ('MoisDate', models.DateField()),
                ('MoisNom', models.CharField(max_length=300)),
                ('SemaineCode', models.IntegerField()),
                ('SemaineDate', models.DateField()),
                ('SemaineNom', models.CharField(max_length=300)),
                ('JourDelannée', models.IntegerField()),
                ('JourDelannéeNom', models.CharField(max_length=300)),
                ('JourDuSemestre', models.IntegerField()),
                ('JourDuTrimestre', models.IntegerField()),
                ('JourDuTrimestreNom', models.CharField(max_length=300)),
                ('JourDuMois', models.IntegerField()),
                ('JourDuMoisNom', models.CharField(max_length=300)),
                ('SemaineDelannée', models.IntegerField()),
                ('MoisDelannée', models.IntegerField()),
                ('MoisDelannéeNom', models.CharField(max_length=300)),
                ('MoisDuSemestreNom', models.CharField(max_length=300)),
                ('MoisDuTrimestre', models.IntegerField()),
                ('MoisDuTrimestreNom', models.CharField(max_length=300)),
                ('TrimestreDelannée', models.IntegerField()),
                ('TrimestreDuSemestreNom', models.CharField(max_length=300)),
                ('SemestreDelannée', models.IntegerField()),
                ('SemestreDelannéeNom', models.CharField(max_length=300)),
                ('Annee', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FactFoncier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateDomainFoncier_FK', models.DateField()),
                ('NreConflitAnnComm', models.IntegerField()),
                ('NbreIndustri_FoncComm', models.IntegerField()),
                ('SuperfiAlloueIndustri', models.IntegerField()),
                ('NbreIndustri_FoncCommMoy', models.IntegerField()),
                ('SupTypeFoncier', models.IntegerField()),
                ('SuperficConced', models.IntegerField()),
                ('SuperficExploite', models.IntegerField()),
                ('Superfic_Deja_Exploite', models.IntegerField()),
                ('IdFoncier_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foncier.dimfoncier')),
                ('IdGouvFoncier_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foncier.dimfonciergouvernanc')),
            ],
        ),
    ]
